apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata: 
  name: http-proto-threat-campaign-dataguard-blocking
  namespace: nginx-plus-ingress-ns
spec:
  policy:
    name: http_proto_threat_campaign_dataguard_blocking
    template: 
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    response-pages:
    - responseContent: '{"Custom WAF Block Response":{"supportid"="<%TS.request.ID()%>"}}'
      responseHeader: 'HTTP/1.1 302 OK\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nConnection:close'
      responseActionType: custom
      responsePageType: default
    blocking-settings:
      violations:
      - name: VIOL_DATA_GUARD
        alarm: true
        block: true
      - name: VIOL_HTTP_PROTOCOL
        alarm: true
        block: true
      - name: VIOL_THREAT_CAMPAIGN
        alarm: true
        block: true
    data-guard:
      enabled: true
      maskData: true
      creditCardNumbers: true
      usSocialSecurityNumbers: true
      enforcementMode: ignore-urls-in-list
      enforcementUrls: []
