# This CRD support for Terraform is still in beta - https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform/ - hence we still stick to YAML execution through kubectl

apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: echo-api-virtual-server-route
  namespace: microservice-namespace
spec:
  ingressClassName: microproxy
  host: localhost
  upstreams:
    - name: echo-service-upstream 
      service: echo-service
      port: 8080
      lb-method: round_robin
      max-fails: 1
      max-conns: 32
      keepalive: 32
      connect-timeout: 30s
      read-timeout: 30s
      send-timeout: 30s
      next-upstream: "error timeout non_idempotent"
      next-upstream-timeout: 5s
      next-upstream-tries: 10
      client-max-body-size: 1m
  subroutes:
  - path: /helloworld
    matches:
      - conditions:
        - variable: $request_method
          value: GET
        action:
          pass: echo-service-upstream
    action:
      return:
        code: 405
        type: application/json
        body: '{\"status\":405,\"message\":\"Hiya, Method you requested is not allowed\"} \n'
---
# Supported NGINX variables: $args, $http2, $https, $remote_addr, $remote_port, $query_string, $request, $request_body, $request_uri, $request_method, $scheme