# This CRD support for Terraform is still in beta - https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform/ - hence we still stick to YAML execution through kubectl

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtual-server
  namespace: microservice-namespace
spec:
  ingressClassName: microproxy
  host: localhost
  http-snippets: |
    gunzip on; # Decompress IdP responses if necessary
    auth_jwt_claim_set $idp_issuer          iss;
    auth_jwt_claim_set $customer_id         sub;
    auth_jwt_claim_set $audience         aud;
    auth_jwt_claim_set $weather_role        permissions;
    proxy_cache_path /var/cache/nginx/jwk levels=1 keys_zone=jwk:1m max_size=10m;
    map $weather_role $isAdmin {
        "admin" 1;
        default 0;
    }
    # Verify the aud claim whether the token is issued to the client for differnt resource access.
    map $audience $isAudienceAllowed { 
        "https://rajeshbavan.ddns.net/v1/partner" 1;
        default                    0;
    }
    map $idp_issuer $isValidIssuer {
        "https://brajesh.au.auth0.com/" 1;
        default                                                          0;
    }
  routes:
  - path: /helloworld
    route: microservice-namespace/echo-api-virtual-server-route
  - path: /weather
    route: microservice-namespace/weather-api-virtual-server-route  
---
# Supported NGINX variables: $args, $http2, $https, $remote_addr, $remote_port, $query_string, $request, $request_body, $request_uri, $request_method, $scheme